USE [master]
GO

/****** Object:  Database [VehicleSalesDB]    Script Date: 11/12/2024 3:37:22 PM ******/
CREATE DATABASE [VehicleSalesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VehicleSalesDB', FILENAME = N'C:\Users\Nikola\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\VehicleSalesDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VehicleSalesDB_log', FILENAME = N'C:\Users\Nikola\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\VehicleSalesDB.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VehicleSalesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VehicleSalesDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [VehicleSalesDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [VehicleSalesDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [VehicleSalesDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [VehicleSalesDB] SET ARITHABORT ON 
GO

ALTER DATABASE [VehicleSalesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VehicleSalesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [VehicleSalesDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [VehicleSalesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [VehicleSalesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VehicleSalesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VehicleSalesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET RECOVERY FULL 
GO

ALTER DATABASE [VehicleSalesDB] SET  MULTI_USER 
GO

ALTER DATABASE [VehicleSalesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VehicleSalesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VehicleSalesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VehicleSalesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VehicleSalesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VehicleSalesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VehicleSalesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [VehicleSalesDB] SET  READ_WRITE 
GO

